version: '3'

services: 

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: ingrena-db
    restart: always    
    tty: true  #Habilita a interação
    volumes: 
      - ./mysql:/var/lib/mysql
      - ./script-bd:/docker-entrypoint-initdb.d
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_PASSWORD=123456
      - MYSQL_USER=anderson
    healthcheck:
      test: mysql --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD -e 'select 1;'
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55
    networks:
      - ingrena-network

  app:
    build:
      context: node
    container_name: ingrena-app        
    tty: true
    restart: always 
    ports: 
      - "3000:3000"
    networks: 
      - ingrena-network     
    healthcheck:
      test: curl -f http://ingrena-app:3000/healthcheck
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55
    depends_on: 
      db:
        condition: service_healthy 
  
  nginx:
    build:
      context: nginx
    container_name: ingrena-nginx
    restart: always 
    networks: 
      - ingrena-network
    ports: 
      - "8080:80"
    depends_on: 
      - app
      - db
    

networks: 
  ingrena-network:
    driver: bridge